### ISSUE TITLE
Payment with VISA change order status to cancelled

### ISSUE THREAD

**Issue by artiumedia** [bambora/payform-magento#1]
I faced this issue with Bambora payform, for customers using VISA cards, every payment is getting canceled on the status even though from Payform dashboard we can see from transaction Details that payment is settled however Bambora server send to our magento following data: 
Bambora PayForm - payment cancelled - order number:xxxxx
and then the order status become Canceled. This is some bug I guess ?! or any ideas what could cause this matters. Note! with MasterCards all work fine.

**Comment by kkarein** [comment]
Please contact our customer support (payform@bambora.com) with your PayForm account details and some details about your transactions (e.g. datetime and amount) and we can check this out.
